# UV Configuration for dotfiles
# This file contains UV-specific settings

[tool.uv]
# Python version to use for new projects
python = "3.11"

# Default package sources
sources = ["PyPI"]

# Enable pre-release packages (optional)
prerelease = false

# Cache directory
cache-dir = "~/.cache/uv"

# Default virtual environment location
venv-path = ".venv"

# Package installation settings
[tool.uv.pip]
# Use system packages when possible
system = true

# Install packages in editable mode by default
editable = false

# Development dependencies
[tool.uv.dev-dependencies]
# Common development tools
pytest = "^7.0.0"
black = "^23.0.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"

# Project templates
[tool.uv.templates]
# Default template for new projects
default = "minimal"

# Available templates
[tool.uv.templates.minimal]
description = "Minimal Python project"
files = [
    "pyproject.toml",
    "src/__init__.py",
    "tests/__init__.py",
    "README.md"
]

[tool.uv.templates.web]
description = "Web application project"
files = [
    "pyproject.toml",
    "src/__init__.py",
    "src/app.py",
    "tests/__init__.py",
    "README.md",
    "requirements.txt"
]
